/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32L476xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	for(;;);
}

void EXTI0_IRQHandler() {
	GPIO_IRQHandling(0);
}
void EXTI1_IRQHandler() {
	GPIO_IRQHandling(1);
}
void EXTI2_IRQHandler() {
	GPIO_IRQHandling(2);
}
void EXTI3_IRQHandler() {
	GPIO_IRQHandling(3);
}
void EXTI4_IRQHandler() {
	GPIO_IRQHandling(4);
}

/*
void EXTI9_5_IRQHandler() {
	GPIO_IRQHandling(5);
}
void EXTI15_10_IRQHandler() {
	GPIO_IRQHandling(10);
}*/
